name = "GridapWorkshop"
authors = ["Santiago Badia <santiago.badia@monash.edu>", "Alberto F. Martin-Huertas <alberto.f.martin@anu.edu.au>", "Jordi Manyer <jordi.manyer@monash.edu>"]
version = "0.1.0"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
GridapPETSc = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"

[extras]
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
